### PR TITLE
Fix #2

### LINKED ISSUE #2: Add tests
Better later than never. This project needs tests badly.

### PR DESCRIPTION
**Pull request by noijd**
This PR adds RSpec, with a dummy Rails app that is being used on the tests.

I have also added Guard, with a custom Guardfile, so testing would be easier.

### CODE REVIEW

**Comment by noijd** [comment]
I don't know if this should be treatred as a major or minor change: @mitio you decide.

**Comment by mitio** [comment]
This looks as a good start! Thanks :)

Why did you decide to not list the development dependencies explicitly in the gemfile?

As for versioning, I don't think we need to release a new version for this. This change contains no functional changes.

**Comment by noijd** [comment]
It's a personal preference; I prefer listing only the runtime dependencies on the `.gemspec`, because that are the unavoidable ones.

It also has another effect: if you move some of that development dependencies to the `.gemspec`, RSpec (and Guard as a consequence) isn't initialized correctly.
I wasn't sure why, but as I prefered the `Gemfile` style, I didn't go deep.

**Comment by mitio** [comment]
Thanks for clarifying that. I think it is not a problem.

**Pull request merged**
